### ISSUE TITLE
ImportError: cannot import name url_encode

### ISSUE THREAD

**Issue by augustomurri** [rbernardes/nginx-pgadmin#1]
Hello, here python lib/python2.7/site-packages/pgadmin4/setup.py i receive this error
any suggestion?

`(.pgadmin4) root@ODOO-FT:~/.pgadmin4/lib/python2.7/site-packages/pgadmin4# python setup.py
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from pgadmin.model import db, User, Version, ServerGroup, Server, \
  File "/root/.pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/__init__.py", line 25, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore, current_user
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_security/core.py", line 28, in <module>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_security/forms.py", line 17, in <module>
    from flask_wtf import FlaskForm as BaseForm
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name url_encode
`

**Comment by rbernardes** [comment]
It looks like you're using python 3 instead of Python 2

https://stackoverflow.com/questions/44031471/importerror-cannot-import-name-urlencode-when-trying-to-install-flask-ext-sto

**Comment by augustomurri** [comment]
Python2.7

`(.pgadmin4) root@ODOO-FT:~/.pgadmin4/lib/python2.7/site-packages/pgadmin4# python
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> quit();
(.pgadmin4) root@ODOO-FT:~/.pgadmin4/lib/python2.7/site-packages/pgadmin4# python setup.py
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from pgadmin.model import db, User, Version, ServerGroup, Server, \
  File "/root/.pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/__init__.py", line 25, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore, current_user
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_security/core.py", line 28, in <module>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_security/forms.py", line 17, in <module>
    from flask_wtf import FlaskForm as BaseForm
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name url_encode
(.pgadmin4) root@ODOO-FT:~/.pgadmin4/lib/python2.7/site-packages/pgadmin4#
`

**Comment by rbernardes** [comment]
Ok, i reproduce the error:

python2.7 /home/rbernardes/.pgadmin4/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py

_Traceback (most recent call last):
  File "/home/rbernardes/.pgadmin4/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py", line 40, in <module>
    import config
  File "/home/rbernardes/.pgadmin4/lib/python2.7/site-packages/pgadmin4/config.py", line 30, in <module>
    from pgadmin.utils import env, IS_PY2, IS_WIN, fs_short_path
  File "/home/rbernardes/.pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/__init__.py", line 19, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'_

 **pip install --upgrade werkzeug==0.16.1**
_The directory '/home/rbernardes/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/rbernardes/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting werkzeug==0.16.1
  Downloading https://files.pythonhosted.org/packages/c2/e4/a859d2fe516f466642fa5c6054fd9646271f9da26b0cac0d2f37fc858c8f/Werkzeug-0.16.1-py2.py3-none-any.whl (327kB)_
    100% |████████████████████████████████| 327kB 16.3MB/s
_Installing collected packages: werkzeug
  Found existing installation: Werkzeug 1.0.0
    Uninstalling Werkzeug-1.0.0:
      Successfully uninstalled Werkzeug-1.0.0
Successfully installed werkzeug-0.16.1
You are using pip version 18.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command._
 
**python2.7 /home/rbernardes/.pgadmin4/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py**
Starting pgAdmin 4. Please navigate to http://0.0.0.0:5050 in your browser.
 * Serving Flask app "pgadmin" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off

**Comment by augustomurri** [comment]
thanks, solved
i need to install some flask libraries after that

**Comment by rbernardes** [comment]
:)
